update questionario q 
set q.SEQ_TIPO_ESCOPO_RESPOSTA = (select SEQ_TIPO_ESCOPO_RESPOSTA from tipo_escopo_resposta where COD_TIPO_ESCOPO = 'TRIBUNAL')
WHERE SEQ_TIPO_ESCOPO_RESPOSTA is null;


update questionario
set DAT_PUBLICACAO = DAT_ATIVACAO_FORMULARIO,
USU_PUBLICACAO = USU_CRIACAO_QUESTIONARIO
WHERE DAT_PUBLICACAO IS NULL;


update questionario
set DSC_STATUS = 'PUBLICADO'
WHERE DAT_PUBLICACAO IS NOT NULL and DSC_STATUS = 'RASCUNHO';
